name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}

      - name: Git setup
        run: |
          git config --global user.email "meap@cin.ufpe.br"
          git config --global user.name "Mateus Elias"

      - name: Git fetch
        run: |
          git fetch --all
          git branch -a

      - name: Create the .env file
        run: |
          echo 'VITE_GOOGLE_MAPS_API_KEY="${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}"' > .env

      - name: Build & Deploy
        run: |
          cd front-end
          npm install
          npm run build
          npm run deploy